package com.gov.licence.workflow;
import java.io.*;
import java.nio.file.*;
import java.sql.*;
import java.util.Properties;
/** One file database outside the deployed WAR; connections are closed after each operation. */
public final class Database {
    private final String url;
    public Database(String url) {
        this.url=url;
        try { Class.forName("org.h2.Driver"); }
        catch(ClassNotFoundException ex){throw new IllegalStateException("H2 database driver is missing",ex);}
        initialize();
    }
    public static Database local() {
        String directory=System.getProperty("licence.data.dir");
        if(directory==null || directory.isBlank()) directory=System.getenv("LICENCE_DATA_DIR");
        if(directory==null || directory.isBlank()) directory=Path.of(System.getProperty("user.home"),"BusinessLicenceRenewal-data").toString();
        try {
            Path path=Path.of(directory).toAbsolutePath().normalize(); Files.createDirectories(path);
            if(path.toString().contains(";")) throw new IllegalArgumentException("Data directory cannot contain a semicolon");
            return new Database("jdbc:h2:file:"+path.resolve("licences").toString().replace('\\','/'));
        } catch(IOException ex){throw new IllegalStateException("Cannot create licence data directory",ex);}
    }
    public Connection connect() throws SQLException {return DriverManager.getConnection(url,"sa","");}
    private void initialize() {
        try(Connection c=connect(); Statement s=c.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS app_users (id BIGINT PRIMARY KEY, username VARCHAR(50) UNIQUE NOT NULL, full_name VARCHAR(100) NOT NULL, role VARCHAR(30) NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS licence_records (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner_id BIGINT NOT NULL REFERENCES app_users(id), registration_number VARCHAR(40) UNIQUE NOT NULL, business_name VARCHAR(150) NOT NULL, trade_category VARCHAR(80) NOT NULL, annual_turnover DECIMAL(15,2) NOT NULL CHECK(annual_turnover>=0), expiry_date DATE NOT NULL, contact_email VARCHAR(120) NOT NULL, contact_phone VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL CHECK(status IN ('SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED')), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, reviewer_id BIGINT REFERENCES app_users(id), remarks VARCHAR(1000), decided_at TIMESTAMP)");
            s.execute("CREATE TABLE IF NOT EXISTS audit_remarks (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, record_id BIGINT NOT NULL REFERENCES licence_records(id), officer_id BIGINT NOT NULL REFERENCES app_users(id), action_taken VARCHAR(20) NOT NULL, remarks_text VARCHAR(1000) NOT NULL, recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
            s.execute("CREATE INDEX IF NOT EXISTS idx_licence_owner ON licence_records(owner_id)");
            Properties users=new Properties();
            try(InputStream in=Database.class.getResourceAsStream("/demo-users.properties")) {
                if(in==null) throw new IllegalStateException("Demo users missing"); users.load(in);
            }
            try(PreparedStatement ps=c.prepareStatement("MERGE INTO app_users(id,username,full_name,role) KEY(id) VALUES(?,?,?,?)")) {
                for(String key:users.stringPropertyNames()) if(key.endsWith(".id")) {
                    String name=key.substring(0,key.length()-3);
                    ps.setLong(1,Long.parseLong(users.getProperty(key))); ps.setString(2,name);
                    ps.setString(3,users.getProperty(name+".name")); ps.setString(4,users.getProperty(name+".role")); ps.executeUpdate();
                }
            }
        } catch(SQLException | IOException ex){throw new IllegalStateException("Cannot initialize licence database",ex);}
    }
}
