<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Business Licence Renewal</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/workflow.css"></head><body>
<header><a class="brand" href="${pageContext.request.contextPath}/dashboard">Business Licence Renewal</a><form method="post" action="${pageContext.request.contextPath}/logout"><input type="hidden" name="csrfToken" value="${sessionScope.csrfToken}"><button id="logout-button" class="secondary" type="submit">Sign out</button></form></header>
<main class="narrow"><a href="${pageContext.request.contextPath}/dashboard">← Dashboard</a><section class="panel">
<h1 id="tracking-id">Application APP-<c:out value="${application.id}"/></h1>
<c:if test="${param.result == 'saved'}"><p id="application-success" class="notice" role="status">Application saved successfully.</p></c:if>
<c:if test="${not empty error}"><p id="decision-error" class="error" role="alert"><c:out value="${error}"/></p></c:if>
<dl class="details"><dt>Status</dt><dd id="application-status"><c:out value="${application.status}"/></dd><dt>Applicant</dt><dd><c:out value="${application.ownerName}"/></dd><dt>Business name</dt><dd><c:out value="${application.businessName}"/></dd><dt>Registration number</dt><dd><c:out value="${application.registrationNumber}"/></dd><dt>Trade category</dt><dd><c:out value="${application.tradeCategory}"/></dd><dt>Annual turnover (INR)</dt><dd><c:out value="${application.annualTurnover}"/></dd><dt>Current licence expiry</dt><dd><c:out value="${application.expiryDate}"/></dd><dt>Contact email</dt><dd><c:out value="${application.contactEmail}"/></dd><dt>Contact phone</dt><dd><c:out value="${application.contactPhone}"/></dd><dt>Submitted at</dt><dd><c:out value="${application.createdAt}"/></dd><dt>Updated at</dt><dd><c:out value="${application.updatedAt}"/></dd>
<c:if test="${not empty application.remarks}"><dt>Officer remarks</dt><dd id="officer-remarks"><c:out value="${application.remarks}"/></dd><dt>Reviewed by</dt><dd><c:out value="${application.reviewerName}"/></dd><dt>Decision at</dt><dd><c:out value="${application.decidedAt}"/></dd></c:if></dl>
<c:if test="${owner && application.editable}"><div class="actions"><a class="button" id="edit-application" href="${pageContext.request.contextPath}/owner/records/edit?id=${application.id}">Edit application</a><form method="post" action="${pageContext.request.contextPath}/owner/records/delete"><input type="hidden" name="csrfToken" value="${sessionScope.csrfToken}"><input type="hidden" name="id" value="${application.id}"><label class="confirm"><input type="checkbox" required> Confirm permanent deletion of this submitted application</label><button class="danger" id="delete-application" type="submit">Delete application</button></form></div></c:if>
<c:if test="${!owner && application.pending}"><h2>Review application</h2>
<c:if test="${application.editable}"><form method="post" action="${pageContext.request.contextPath}/officer/records/start"><input type="hidden" name="csrfToken" value="${sessionScope.csrfToken}"><input type="hidden" name="id" value="${application.id}"><button class="secondary" id="start-review" type="submit">Mark under review</button></form></c:if>
<form id="decision-form" method="post" action="${pageContext.request.contextPath}/officer/records/decide"><input type="hidden" name="csrfToken" value="${sessionScope.csrfToken}"><input type="hidden" name="id" value="${application.id}"><label for="remarks">Decision remarks (required)<textarea id="remarks" name="remarks" rows="4" maxlength="1000" required><c:out value="${param.remarks}"/></textarea></label><div class="actions"><button id="approve-application" name="decision" value="APPROVED" type="submit">Approve renewal</button><button id="reject-application" class="danger" name="decision" value="REJECTED" type="submit">Reject renewal</button></div></form></c:if>
<c:if test="${!application.pending}"><p class="muted">The decision is final. This application cannot be edited or deleted.</p></c:if>
</section></main></body></html>
